version: '3.7'

services:

  next:
    volumes:
      - portfolio:/app
      - /app/node_modules
    build:
      context: /home/ubuntu/next_portfolio
#    expose:
#     - 3000
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - portfolio:/portfolio
      - ./nginx/portfolio.conf:/etc/nginx/conf.d/portfolio.conf
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/www/:/var/www/certbot
      # - ns-static:/ns-static
      # - r-static:/r-static
      
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf/:/etc/letsencrypt
      - ./certbot/www/:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email paulo@desouza-tech.com --agree-tos -d desouza-tech.com


#   newspace_gunicorn:
#     volumes:
#       - ns-static:/static
#     env_file:
#       - /home/ubuntu/newspace360_django/.env
#     build:
#       context: /home/ubuntu/newspace360_django

#     expose: 
#      - 8000
# #    ports: 
# #      - "8000:8000"


#   reception_gunicorn:
#     volumes:
#       - r-static:/static
#     env_file:
#       - /home/ubuntu/reception-app-django/.env
#     build:
#       context: /home/ubuntu/reception-app-django
#     expose: 
#      - 8002
# #    ports: 
# #      - "8002:8002"

  # ghost:
  #   image: ghost:5-alpine
  #   restart: always
  #   expose: 
  #    - 2368
  #   environment:
  #     database__client: mysql
  #     database__connection__host: db
  #     database__connection__user: root
  #     database__connection__password: example
  #     database__connection__database: ghost
  #     url: http://covil.art

  #   volumes:
  #     - ghost:/var/lib/ghost/content

  # db:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #   volumes:
  #     - db:/var/lib/mysql


volumes:
  # ns-static:
  # r-static: 
  portfolio:
  # ghost:
  # db: