version: '3.7'

services:
  certbot:
    image: certbot/certbot:latest
    command: certonly --dry-run --webroot --webroot-path=/var/www/certbot/ --email paulo@desouza-tech.com --agree-tos --no-eff-email -d desouza-tech.com -d www.desouza-tech.com
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  next:
    volumes:
      - portfolio:/app
      - /app/node_modules
    build:
      context: /home/ubuntu/next_portfolio
#    expose:
#     - 3000
    ports:
      - "3000:3000"

  nginx:
    build: ./nginx
    volumes:
      # - ns-static:/ns-static
      # - r-static:/r-static
      - portfolio:/portfolio
      - ./nginx/conf/:/etc/nginx/conf.d/:rw
      - ./certbot/www/:/var/www/certbot/:rw
      
    ports:
      - 80:80
      - 443:443

    restart: always
    depends_on:
      # - newspace_gunicorn
      # - reception_gunicorn
      - next
      # - ghost



#   newspace_gunicorn:
#     volumes:
#       - ns-static:/static
#     env_file:
#       - /home/ubuntu/newspace360_django/.env
#     build:
#       context: /home/ubuntu/newspace360_django

#     expose: 
#      - 8000
# #    ports: 
# #      - "8000:8000"


#   reception_gunicorn:
#     volumes:
#       - r-static:/static
#     env_file:
#       - /home/ubuntu/reception-app-django/.env
#     build:
#       context: /home/ubuntu/reception-app-django
#     expose: 
#      - 8002
# #    ports: 
# #      - "8002:8002"

  # ghost:
  #   image: ghost:5-alpine
  #   restart: always
  #   expose: 
  #    - 2368
  #   environment:
  #     database__client: mysql
  #     database__connection__host: db
  #     database__connection__user: root
  #     database__connection__password: example
  #     database__connection__database: ghost
  #     url: http://covil.art

  #   volumes:
  #     - ghost:/var/lib/ghost/content

  # db:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #   volumes:
  #     - db:/var/lib/mysql


volumes:
  # ns-static:
  # r-static: 
  portfolio:
  # ghost:
  # db: