FROM nginx:1.19.0-alpine


#COPY ./covil.conf /etc/nginx/conf.d/covil.conf
#COPY ./newspace.conf /etc/nginx/conf.d/newspace.conf
COPY ./portfolio.conf /etc/nginx/conf.d/portfolio.conf
#COPY ./reception.conf /etc/nginx/conf.d/reception.conf




